SELECT *
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

SELECT COUNTRY_NAME
FROM REGIONS NATURAL JOIN COUNTRIES 
WHERE REGION_ID = 1;

SELECT ORG_NAME, COUNTRY_NAME
FROM ORGANIZATIONS NATURAL JOIN ORG_COUNTRY
NATURAL JOIN COUNTRIES;