spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/egalli64/microservices-config
          default-label: main
          clone-on-start: true
          timeout: 10

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always

---
# Docker profile configuration
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: config-server